/**
 * STATE.JS — Shelf Ready
 * ─────────────────────────────────────────────────────────────
 * The single state object. Every tool reads/writes through this
 * module. Nothing in the app talks to localStorage directly
 * except this file. That's the rule — it's what keeps "no
 * duplicated save logic" true as the app grows.
 *
 * Schema (see Master Content Matrix for what each field means):
 *
 * {
 *   meta: { version, createdAt, lastOpenedAt },
 *   activeProjectId: "proj_xxx" | null,
 *   projects: {
 *     "proj_xxx": {
 *       id, name, createdAt, updatedAt,
 *       discover: { workingTitle, concept, reader, promise, positioning,
 *                   positioningComps: [], completedAt },
 *       design:   { ...future phases, stubbed for now },
 *       write:    { ... },
 *       refine:   { ... },
 *       package:  { ... },
 *       publish:  { ... },
 *       confidence: { conceptClarity, readerClarity, promiseClarity, positioningClarity },
 *       flags: { discoverComplete: bool, ... }
 *     }
 *   },
 *   settings: { highContrast: bool, ttsEnabled: bool, reducedMotion: bool }
 * }
 *
 * Evidence Library is NOT in this object — it's static, read-only,
 * shipped separately in data/evidence.js. Never copy evidence into
 * a project. Always look it up live by Evidence Field Path.
 */

const STORAGE_KEY = 'shelfready_workspace_v1';
const SCHEMA_VERSION = 1;

function emptyWorkspace() {
  return {
    meta: {
      version: SCHEMA_VERSION,
      createdAt: new Date().toISOString(),
      lastOpenedAt: new Date().toISOString()
    },
    activeProjectId: null,
    projects: {},
    settings: {
      highContrast: false,
      ttsEnabled: false,
      reducedMotion: false
    }
  };
}

function emptyProject(name) {
  const id = 'proj_' + Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
  const now = new Date().toISOString();
  return {
    id,
    name: name || 'Untitled Book',
    createdAt: now,
    updatedAt: now,
    discover: {
      workingTitle: '',
      concept: '',
      reader: '',
      promise: '',
      positioning: '',
      positioningComps: ['', ''],
      completedAt: null
    },
    design: {
      spine: { protagonist: '', problem: '', action: '', stakes: '' },
      stressTest: { stakesRemoved: null, protagonistSwapped: null, problemSwapped: null }, // null | true | false
      chapters: [], // [{ id, text }]
      chapterFindings: [], // populated by DesignReview.checkChapterSpine
      completedAt: null
    },
    write: { notes: '', completedAt: null },
    refine: {
      manuscript: null, // { title, subtitle, chapters: [...], overallConfidence, rawWordCount, importedAt }
      findings: [], // [{ inspectionId, severity, data... }] generated by running inspections
      completedAt: null
    },
    package: {
      titleCandidates: [], // [{ id, text }]
      finalTitle: '',
      subtitle: { outcome: '', reader: '', objection: '' },
      finalSubtitle: '',
      coverBrief: { category: '', comps: ['', ''], mood: '', avoid: '' },
      packageFindings: [],
      completedAt: null
    },
    publish: {
      authorBio: '',
      bookDescription: '',
      descriptionFindings: [],
      completedAt: null
    },
    confidence: {
      conceptClarity: 'unset',
      readerClarity: 'unset',
      promiseClarity: 'unset',
      positioningClarity: 'unset'
    },
    flags: {
      discoverComplete: false,
      designComplete: false,
      writeComplete: false,
      refineComplete: false,
      packageComplete: false,
      publishComplete: false
    }
  };
}

/**
 * The Store — small pub/sub wrapper around localStorage.
 * Views subscribe to be re-rendered on any state change.
 */
const Store = (function () {
  let state = load();
  const listeners = new Set();

  function load() {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (!raw) return emptyWorkspace();
      const parsed = JSON.parse(raw);
      if (!parsed.meta || parsed.meta.version !== SCHEMA_VERSION) {
        console.warn('Shelf Ready: workspace schema mismatch, starting fresh.');
        return emptyWorkspace();
      }
      return parsed;
    } catch (err) {
      console.error('Shelf Ready: could not read saved workspace, starting fresh.', err);
      return emptyWorkspace();
    }
  }

  function persist() {
    state.meta.lastOpenedAt = new Date().toISOString();
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    } catch (err) {
      console.error('Shelf Ready: save failed.', err);
      notify({ type: 'save-error', error: err });
      return false;
    }
    return true;
  }

  function notify(event) {
    listeners.forEach((fn) => fn(state, event));
  }

  return {
    getState() {
      return state;
    },

    getActiveProject() {
      if (!state.activeProjectId) return null;
      return state.projects[state.activeProjectId] || null;
    },

    createProject(name) {
      const project = emptyProject(name);
      state.projects[project.id] = project;
      state.activeProjectId = project.id;
      persist();
      notify({ type: 'project-created', projectId: project.id });
      return project;
    },

    setActiveProject(projectId) {
      if (!state.projects[projectId]) return false;
      state.activeProjectId = projectId;
      persist();
      notify({ type: 'project-switched', projectId });
      return true;
    },

    listProjects() {
      return Object.values(state.projects).sort(
        (a, b) => new Date(b.updatedAt) - new Date(a.updatedAt)
      );
    },

    /**
     * Update a field on the active project using a dot path,
     * e.g. updateField('discover.reader', 'Solo consultants...')
     */
    updateField(dotPath, value) {
      const project = this.getActiveProject();
      if (!project) return false;
      const parts = dotPath.split('.');
      let node = project;
      for (let i = 0; i < parts.length - 1; i++) {
        node = node[parts[i]];
      }
      node[parts[parts.length - 1]] = value;
      project.updatedAt = new Date().toISOString();
      persist();
      notify({ type: 'field-updated', path: dotPath, value });
      return true;
    },

    setConfidence(key, level) {
      const project = this.getActiveProject();
      if (!project) return false;
      project.confidence[key] = level;
      persist();
      notify({ type: 'confidence-updated', key, level });
      return true;
    },

    completePhase(phaseName) {
      const project = this.getActiveProject();
      if (!project) return false;
      project[phaseName].completedAt = new Date().toISOString();
      project.flags[phaseName + 'Complete'] = true;
      persist();
      notify({ type: 'phase-completed', phaseName });
      return true;
    },

    updateSettings(patch) {
      Object.assign(state.settings, patch);
      persist();
      notify({ type: 'settings-updated', patch });
    },

    subscribe(fn) {
      listeners.add(fn);
      return () => listeners.delete(fn);
    },

    /** Export: 'project' exports only the active project; 'workspace' exports everything. */
    exportData(scope) {
      if (scope === 'project') {
        const project = this.getActiveProject();
        if (!project) return null;
        return {
          exportType: 'shelfready-project',
          schemaVersion: SCHEMA_VERSION,
          exportedAt: new Date().toISOString(),
          project
        };
      }
      return {
        exportType: 'shelfready-workspace',
        schemaVersion: SCHEMA_VERSION,
        exportedAt: new Date().toISOString(),
        workspace: state
      };
    },

    importData(payload) {
      try {
        if (payload.exportType === 'shelfready-project' && payload.project) {
          state.projects[payload.project.id] = payload.project;
          state.activeProjectId = payload.project.id;
        } else if (payload.exportType === 'shelfready-workspace' && payload.workspace) {
          state = payload.workspace;
        } else {
          throw new Error('Unrecognized file format.');
        }
        persist();
        notify({ type: 'data-imported' });
        return { ok: true };
      } catch (err) {
        return { ok: false, error: err.message };
      }
    }
  };
})();
